import cv2
from config import rtsp_url
import imutils
from imutils.video import VideoStream

# replace this with the url generated by the Wyze app

vs = VideoStream(rtsp_url).start()

while True:
    frame = vs.read()

    if frame is None:
        continue

    frame = imutils.resize(frame, width=1200)

    cv2.imshow('WyzeCam', frame)

    key = cv2.waitKey(1) & 0xFF

    if key == ord('q'): #use 'q' to close your cam window
        break

cv2.destroyAllWindows()
vs.stop()
